name: Merge VPN Configs

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        persist-credentials: false

    - name: Download, process and merge configs
      run: |
        echo "# Merged VPN Config - Updated on $(date -u)" > merged_config.txt
        echo "" >> merged_config.txt

        SOURCES="\
        https://raw.githubusercontent.com/sakha1370/OpenRay/refs/heads/main/output_iran/iran_top100_checked.txt,\
        https://raw.githubusercontent.com/4n0nymou3/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs_tested.txt,\
        https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/hy2.html,\

https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/refs/heads/main/Config/vless.txt,\
        https://raw.githubusercontent.com/Created-By/Telegram-Eag1e_YT/main/%40Eag1e_YT"

        IFS=',' read -ra URLS <<< "$SOURCES"

        COUNT=1

        for URL in "${URLS[@]}"; do
          echo "## Source $COUNT" >> merged_config.txt

          curl -s "$URL" \
          | sed '/^\s*$/d' \
          | sed 's/#.*/#@teleking_vip/g' \
          >> merged_config.txt

          echo -e "\n\n" >> merged_config.txt

          COUNT=$((COUNT+1))
        done

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/kingowow/Kingo-vpn.git

        git add merged_config.txt

        git diff --cached --quiet || (
          git commit -m "Auto update merged_config.txt"
          git push origin main
        )
